### PR TITLE
Null dereference check

### PR DESCRIPTION
**Pull request by ksuther**
Fixes a static analyzer warning.

### CODE REVIEW

**Comment by lbrndnr** [comment]
What happens if you're on an iPad and requesting the high quality data? Does it return the same as the default one with your branch?

Commit `0ab9d82` seems unproductive to my eyes.

**Comment by ksuther** [comment]
I'm not sure what you mean by returning the same as the default one. Using the iPad user agent causes a 720p video to get returned as the first result in the array, if available. This causes LBYouTubeVideoQualityLarge to return the hd720 result, but the other two options will still return the same thing. Does that answer your question?

0ab9d82 prevents a null dereference if you pass in null for error. The only place this method is called is from connectionDidFinishLoading: so this isn't going to happen unless someone uses the method directly, but it silences the static analyzer.

**Comment by lbrndnr** [comment]
Would you mind explaining me once more why the null dereference check is necessary?
I'd be happy to merge this if you could pull the current branch first.

**Comment by ksuther** [comment]
A bit late, but I merged everything back in to my branch. The null dereference is to prevent a static analyzer warning. Just try running the analyzer on the current master, you'll see the warning about it.

**Pull request merged**
