### PR TITLE
New parser using regular expression

### PR DESCRIPTION
**Pull request by pcevandijk**
I have changed the parser so it now uses 1 regular expression to extract the video URL's from the HTML.

This regular expression can be changed. For example in my project i have the regular expression in a settings file on my server. If the expression has to change (because of a HTML change by YouTube) i change the regular expression on my server and the app will work again. In this way you dont have to submit a new binary to Apple and wait till its aproved. 

Note: This is my first regular expression ever, so feel free to improve it :-)

### CODE REVIEW

**Comment by dawildcat** [comment]
Hi,

I've implemented your regular expression solution (also downloading fro a server - top tip!!) and it was working fine until Sunday night. Would you have any update for the regular expression to address the latest youtube changes?

Thanks :)

**Comment by pcevandijk** [comment]
Over here i have no problems. Which Youtube url goes wrong?

**Comment by rrroni** [comment]
Hi,

Excellent concept here to incorporate the server, thank you.  I've encountered these issues since Monday morning, too, for example ekzHIouo8Q4, 8dM5QYdTo08, and AgFeZr5ptV8.  Any ideas for working this out?

Thanks!

**Comment by lbrndnr** [comment]
@rrroni  @pcevandijk's solution works fine for those video ids.

**Pull request merged**
