### PR TITLE
Separating extraction from view

### PR DESCRIPTION
**Pull request by muccy**
In those commits:
- I separated extractor from view, splitting in two classes
- I supported iOS 4 introducing JSONKit dependency

### CODE REVIEW

**Comment by zakdances** [comment]
Why kind of file does the extracted URL point to? an FLV? an MP4?

**Comment by lbrndnr** [comment]
It's an mp4 file I guess.

I like the idea of separating things but I'd rather prefer a controller like MPMoviePlayerController.

**Comment by zakdances** [comment]
I just want something that can pull the URL...I'll deal with the player myself. I'd really like to know for sure what type of file the URL points to.

**Comment by lbrndnr** [comment]
Well a controller is actually the right way to do this. I just tried to publish my approach as soon as possible so I didn't really think about that. Well figure it out on your own. When you play a youtube video in the iOS simulator, it logs some stuff. Just check it out in the console. It prints the direct URL to the file.

**Comment by zakdances** [comment]
Your approach is great, it just would be even more useful if you separated the URL extraction object from the player object. That way they could be used separately OR together. Basically what I'm trying to is be able to fully download/buffer the clip in one view controller, then play the clip later in another view controller. I also want to create a progress bar for the download.

**Pull request merged**
