### PR TITLE
YouTube JSON structure change

### PR DESCRIPTION
**Pull request by willex**
YouTube changed their JSON structure again; nested JSON parameter was changed from 'video' to 'player_data'.

### CODE REVIEW

**Comment by jezcomputer** [comment]
Seems still not be working on vevo videos.

**Comment by absolute-heike** [comment]
duplicate with https://github.com/larcus94/LBYouTubeView/pull/71

:-)

@jezcomputer Do you have a link, so we can check, why this happens?

Could be, that vevo is blocking mobile devices to push their mobile app!

**Comment by jezcomputer** [comment]
Seems to be all vevo videos have the issue ; e.g. Search m.youtube.com   vevo One Direction - Best Song Ever

e.g. http://www.youtube.com/watch?v=o_v9MY_FMcw

**Comment by absolute-heike** [comment]
Unfortunately i cannot access this Video from germany ;-)

But I guess you wouldn't be able to play the video on the mobile browser either.

Have you tried to open the video on mobile safari?

**Comment by willex** [comment]
Vevo has issues for some time already - I think they blogged external access to their content and thats why you cannot play it (URL extraction works fine AFAIK)

**Comment by jezcomputer** [comment]
Maybe we have to use a different approach as per the https://github.com/rg3/youtube-dl project ?

**Comment by PixelPartner** [comment]
They seem to have the same problem and commited a fix just an hour ago.

2013/9/6 jezcomputer notifications@github.com

**Comment by YoniTsafir** [comment]
+1 please merge

**Comment by ttv100682** [comment]
I think change the the key json in code is not good solution. Maybe the json structure changes frequently :-1: .

**Comment by ttv100682** [comment]
I am thinking solution like this: my app when starting-up will get some data from server, so I will let some config for youtube video's keyword json :) then server response config keyword json to the app. The app will use that key json to extract youtube video. Is it :+1: ?

**Comment by pcevandijk** [comment]
At this moment i'm writing a new parser using a regular expression to extract the URL's.
This works fine, also for VEVO video's. 
Big advantage of the regular expression solution is that you can put it in a settings file on your server, and if it needs to be changed all you have to do is fix the regex on your server. 

Almost done testing.

**Comment by lbrndnr** [comment]
Indeed, the regex of @pcevandijk seems a lot more stable. Merged it at works fine with the mentioned URL.

**Comment by kbalsen2001** [comment]
This fix doesn't seem to work for VEVO videos. I tried the fix on youtube videoid MU8B4XDI3Uw. It opens the player and keeps spinning. Any ideas?

**Comment by kbalsen2001** [comment]
The URL was extracted but it seems to not have the signature. Here's what I got:

2013-09-20 12:37:11.828 LBYouTubeView[12879:907] Did extract video source:http://r15---sn-nwj7knll.c.youtube.com/videoplayback?yms=bS8W4l_uV7s&ratebypass=yes&sver=3&expire=1379729776&upn=SpCtHLva5mY&itag=18&key=yt1&fexp=900225%2C919121%2C930103%2C919363%2C916807%2C929234%2C916611%2C919515%2C924606%2C929117%2C929121%2C929906%2C929907%2C929922%2C929923%2C929127%2C929129%2C929131%2C929930%2C936403%2C925724%2C925726%2C936310%2C925720%2C925722%2C925718%2C925714%2C929917%2C906945%2C929933%2C929935%2C939604%2C906842%2C913428%2C920605%2C937003%2C919811%2C932309%2C913563%2C919373%2C930803%2C908536%2C938701%2C931924%2C934005%2C940501%2C936308%2C909549%2C901608%2C900816%2C912711%2C934507%2C907231%2C936312%2C906001&gcr=us&app=youtube_mobile&source=youtube&ipbits=8&dnc=1&cp=U0hWTldNV19MUENONl9PR0FIOmRQOVoxb196WTJ1&sparams=cp%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cratebypass%2Csource%2Cupn%2Cexpire&id=314f01e170c8dd4c&mt=1379705766&ip=108.233.44.213&ms=au&mv=m&el=watch

**Pull request closed without merging**
